name: Run Maestro Tests (APK already built)

on:
  push:
  pull_request:

jobs:
  maestro-cloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run Maestro tests in Cloud
        uses: mobile-dev-inc/action-maestro-cloud@v1
        with:
          api-key: ${{ secrets.MAESTRO_API_KEY }}
          project-id: ${{ secrets.MAESTRO_CLOUD_PROJECT_ID }}
          app-file: apks/base.apk
          workspace: windows/pomodoro/task
